In [1]:
import numpy as np

In [2]:
a = np.array([2,5,6], dtype = 'int32')
a

array([2, 5, 6])

In [3]:
b = np.array([[1.0, 2.0], [2,3]])
b

array([[1., 2.],
       [2., 3.]])

In [5]:
a.ndim


1

In [6]:
b.ndim

2

In [7]:
b.shape

(2, 2)

In [8]:
a.dtype

dtype('int32')

In [9]:
a.itemsize

4

In [10]:
a.nbytes

12

In [12]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a[1,5]


13

In [15]:
a[:,4]

array([ 5, 12])

In [16]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
a[0,1:-1:2]

array([2, 4, 6])

In [23]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
b[0,1,1]

4

In [25]:
b.shape

(2, 2, 2)

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((1,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]]])

In [30]:
np.full((2,2), 65)

array([[65, 65],
       [65, 65]])

In [31]:
np.random.rand(4,3)

array([[0.87360667, 0.47274786, 0.76884332],
       [0.48902557, 0.74805367, 0.62763604],
       [0.86011792, 0.04925619, 0.21671091],
       [0.717528  , 0.43554817, 0.44920942]])

In [34]:
np.random.randint(10, size=(3,3))

array([[4, 1, 7],
       [2, 4, 6],
       [1, 4, 0]])

In [35]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [40]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
a

array([1, 2, 3])

In [41]:
a = np.array([1,2,3,4])


In [42]:
a+2

array([3, 4, 5, 6])

In [43]:
a*2

array([2, 4, 6, 8])

In [49]:
b = np.array([0,0,1,1])

In [50]:
a + b

array([ 9, 10, 12, 13])

In [51]:
a

array([ 9, 10, 11, 12])

In [52]:
a + b

array([ 9, 10, 12, 13])

In [53]:
np.sin(a)

array([ 0.41211849, -0.54402111, -0.99999021, -0.53657292])

In [54]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]


array([[6., 6.],
       [6., 6.]])

In [55]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [56]:
stats = np.array([[1,2,3],[5,7,8]])
stats

array([[1, 2, 3],
       [5, 7, 8]])

In [57]:
np.min(stats)

1

In [58]:
np.sum(stats)

26

In [60]:
stats = stats.reshape((3,2))
stats

array([[1, 2],
       [3, 5],
       [7, 8]])

In [63]:
a = np.array([1,2,3])
b = np.array([2,3,4])

np.vstack([a,b])
np.hstack([a,b])

array([1, 2, 3, 2, 3, 4])

In [64]:
a > 2

array([False, False,  True])

In [65]:
a[a>2]

array([3])